# minio-nodeport-service.yaml
apiVersion: v1
kind: Service
metadata:
  # 创建一个新服务，避免与 Helm 安装的服务冲突
  name: minio-external-service
  namespace: default
spec:
  # 服务类型为 NodePort
  type: NodePort
  # 使用从 kubectl 命令中查到的稳定标签来选择正确的 Pod
  selector:
    app: minio
    release: minio
  ports:
    # --- 端口 1: 暴露 MinIO S3 API (给程序使用) ---
    - name: api
      protocol: TCP
      port: 9000          # Service 在集群内部的端口
      targetPort: 9000      # MinIO Pod 实际的 API 端口
      nodePort: 30900     # 你想在外部暴露的固定 API 端口

    # --- 端口 2: 暴露 MinIO Web UI (给浏览器使用) ---
    - name: ui-console
      protocol: TCP
      port: 9001          # Service 在集群内部的端口
      targetPort: 9001      # MinIO Pod 实际的 UI 端口
      nodePort: 30901     # 你想在外部暴露的固定 UI 端口