# Feast Feature Server 独立配置
# 使用feast-feature-server chart

image:
  repository: feastdev/feature-server
  tag: "0.46.0"

# 服务配置
service:
  type: ClusterIP
  port: 6566

# 环境变量 - 包含feature_store.yaml配置
env:
  - name: FEATURE_STORE_YAML_BASE64
    value: "cHJvamVjdDogZmVhc3Rfc3RvcmUKcmVnaXN0cnk6IC90bXAvZmVhc3QvcmVnaXN0cnkuZGIKcHJvdmlkZXI6IGxvY2FsCm9ubGluZV9zdG9yZToKICB0eXBlOiByZWRpcwogIGNvbm5lY3Rpb25fc3RyaW5nOiAiZmVhc3QtYmFzZS1yZWRpcy1tYXN0ZXI6NjM3OSIKb2ZmbGluZV9zdG9yZToKICB0eXBlOiBmaWxlCmVudGl0eV9rZXlfc2VyaWFsaXphdGlvbl92ZXJzaW9uOiAyCg=="

# 启动命令 - 使用Python而不是Java
command: ["feast", "serve", "-h", "0.0.0.0"]

# 禁用健康检查探针（避免grpc-health-probe问题）
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

# 资源限制
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi